name: otel-ebpf-profiler
version: '0.130.0'
summary: Whole-system, cross-language profiler for Linux via eBPF.
description: |
  An OpenTelemetry Collector distribution that is made specifically to be used as a whole-system,
  cross-language profiler for Linux via eBPF.
contact: michael.dmitry@canonical.com
license: Apache-2.0
issues: https://github.com/canonical/otel-ebpf-profiler-snap
base: core24
platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]
confinement: classic
apps:
  otel-ebpf-profiler:
    daemon: simple
    # we need to enable service.profilesSupport feature gate to use the profiles pipeline
    command: /bin/otel-ebpf-profiler --feature-gates service.profilesSupport --config /etc/otel-ebpf-profiler/config.yaml
    install-mode: disable
    restart-condition: on-failure
parts:
  config:
    plugin: dump
    source: ./snap/
    source-type: local
    override-build: |
      install -D config.yaml $CRAFT_PART_INSTALL/
  ocb:
    plugin: go
    source: "https://github.com/open-telemetry/opentelemetry-collector.git"
    source-type: "git"
    source-tag: "v0.130.0"
    source-depth: 1
    source-subdir: "cmd/builder"
    build-snaps:
      - go/1.23/stable
    build-environment:
      - CGO_ENABLED: "0"
      - GOOS: linux
    stage:
      - bin/builder
    prime:
      - "-*"
  ebpf-profiler:
    after:
      - ocb
    plugin: dump
    source: .
    build-packages:
      - wget
    override-build: |
      # Create the binary
      wget https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-releases/refs/tags/v0.130.0/distributions/otelcol-ebpf-profiler/manifest.yaml -O ${CRAFT_PART_BUILD}/manifest.yaml
      builder --config="${CRAFT_PART_BUILD}/manifest.yaml"
      install -D -m755 ${CRAFT_PART_BUILD}/_build/otelcol-ebpf-profiler ${CRAFT_PART_INSTALL}/bin/otel-ebpf-profiler
    build-attributes:
      - enable-patchelf